version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_skyway"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_skyway/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_skyway_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_skyway_android"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/flutter_skyway_ios"
    schedule:
      interval: "daily"