name: flutter_skyway_example
description: Demonstrates how to use the flutter_skyway plugin.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_skyway:
    # When depending on this package from a real application you should use:
    #   flutter_skyway: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  permission_handler: ^11.0.1
  # Network
  dio: ^5.2.1+1
  socket_io_client: ^2.0.3+1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.1

  # State management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # Utils
  get_it: ^7.6.4
  flutter_screenutil: ^5.9.0
  json_serializable: ^6.7.1
  equatable: ^2.0.5
  connectivity_plus: ^4.0.2
  top_snackbar_flutter: ^3.1.0
  bot_toast: ^4.0.4
  form_field_validator: ^1.1.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  build_runner:
  retrofit_generator:
  freezed: ^2.3.2

flutter:
  uses-material-design: true
